### PR TITLE
I'm getting permissions too open for my build

### PR DESCRIPTION
**Pull request by byrnedo**
see https://github.com/tonycoco/heroku-buildpack-ember-cli/issues/89

### CODE REVIEW

**Comment by tonycoco** [comment]
I think you should probably just chmod it on your local copy. That way when it is pulled, no errors. Right?

**Comment by byrnedo** [comment]
I thought your compile step writes that file from the config var?

**Comment by byrnedo** [comment]
Just to be clear, its the SSH key written by the build step, from the GIT_SSH_KEY config var, not a key in my repo

**Comment by tonycoco** [comment]
Ahh, that's right. Ok cool. Merging....

**Comment by byrnedo** [comment]
Thanks :)

**Pull request merged**
